---
title: "Nobel winners"
author: "YOU"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

```{r load-packages, message=FALSE}
library(tidyverse)
```

Let's first load the data:

```{r label-me1, eval=FALSE}
nobel <- read_csv(file="c:/Data/Github/ae06/data-raw/nobel.csv")
```

Then let's split the data into two:

```{r label-me2, eval=FALSE}
# stem laureates
nobel_stem <- nobel %>%
  filter(category %in% c("Psysics", "Medicine","Chemistry","Economics"))
  


# non-steam laureates

nobel_nonstem<-nobel%>%
  filter(!category %in% c("Psysics", "Medicine","Chemistry","Economics"))


```

And finally write out the data:

```{r label-me3}
# add code for writing out the two data frames here
write.csv(nobel_stem, file="c:/Data/Github/ae06/data-raw/nobel_stem.csv")
write.csv(nobel_nonstem, file="c:/Data/Github/ae06/data-raw/nobel_nonstem.csv")
```

## References {#references}
1. Assignment Adapted from [Mine Cetinkaya-Rundel's Data Science in a Box](https://github.com/rstudio-education/datascience-box)